// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4dMiyChLWayCbIzzr-v0ar8dFOW11M0',
    appId: '1:1058906408415:web:d77b706dc912063898f06a',
    messagingSenderId: '1058906408415',
    projectId: 'campus-connect-e62ba',
    authDomain: 'campus-connect-e62ba.firebaseapp.com',
    storageBucket: 'campus-connect-e62ba.firebasestorage.app',
    measurementId: 'G-7VB8LMFDXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrSUh_YXJhPz-QQACvE7GJVF__Ze2Kuk',
    appId: '1:1058906408415:android:cbf15a698431e39698f06a',
    messagingSenderId: '1058906408415',
    projectId: 'campus-connect-e62ba',
    storageBucket: 'campus-connect-e62ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx6aS2YBWa9KwnZjJWhV16s0zH3eVfpwM',
    appId: '1:1058906408415:ios:6fe9859299a4347a98f06a',
    messagingSenderId: '1058906408415',
    projectId: 'campus-connect-e62ba',
    storageBucket: 'campus-connect-e62ba.firebasestorage.app',
    iosBundleId: 'com.mikkyboy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4dMiyChLWayCbIzzr-v0ar8dFOW11M0',
    appId: '1:1058906408415:web:6346ccb8a7a5a87a98f06a',
    messagingSenderId: '1058906408415',
    projectId: 'campus-connect-e62ba',
    authDomain: 'campus-connect-e62ba.firebaseapp.com',
    storageBucket: 'campus-connect-e62ba.firebasestorage.app',
    measurementId: 'G-DMZ3VD42ZV',
  );
}
